 development:
   host: localhost:8080
   email: thiyagarajan@moorem.com
   password: test1234
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
 production:
   host: hogarth-group.herokuapp.com
   email: tom.gallagher@theappengineers.com
   password: mooremtech
#   # api_key: <your api key here>